# Generated by Django 5.1.6 on 2025-02-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_thread_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='craeted_by',
            new_name='created_by',
        ),
    ]
