# Generated by Django 5.1.6 on 2025-03-02 03:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_forumreply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislike_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
