# Generated by Django 5.1.3 on 2025-03-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_forumreply_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='category_comment_count',
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
