# Generated by Django 5.1.3 on 2025-03-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_userprofile_category_comment_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category_comment_count',
            field=models.JSONField(default=dict),
        ),
    ]
