# Generated by Django 5.1.3 on 2025-03-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userprofile_category_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category_dislike_count',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category_like_count',
            field=models.JSONField(default=dict),
        ),
    ]
