# Generated by Django 5.1.6 on 2025-04-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_forumreply_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
