# Generated by Django 5.1.6 on 2025-04-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_userprofile_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
