# Generated by Django 5.1.6 on 2025-04-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_userprofile_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='restricted_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
